embedding_size: 64
feat_embed_dim: 64

n_mm_layers: 1
knn_k: [5, 10, 15, 20]
mm_image_weight: 0.1
aggr_mode: ['add']
learning_rate: [0.0001]
reg_weight: [0.001, 0.0005, 0.0001]
ssl_weight: [0.001, 0.0005, 0.0001]
hyper_parameters: ["knn_k", "aggr_mode", "reg_weight", "ssl_weight", "learning_rate"]